{
    "openapi": "3.0.2",
    "info": {
        "title": "Etsy OpenAPI",
        "description": "<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API reference documents endpoints are meant to replace <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://www.etsy.com/developers/documentation\">Etsy's current Open API</a> this year. Use of the API is subject to the <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://www.etsy.com/legal[...]",
        "termsOfService": "https://www.etsy.com/legal/api",
        "contact": {
            "email": "developers@etsy.com"
        },
        "version": "3.0.0",
        "x-logo": {
            "url": "https://img0.etsystatic.com/site-assets/open-api/etsy_logo.png",
            "backgroundColor": "#FFFFFF",
            "altText": "Etsy Logo"
        }
    },
    "servers": [
        {
            "url": "https://openapi.etsy.com",
            "description": "Base url for all Integrations endpoints."
        }
    ],
    "security": [
        {
            "api_key": []
        }
    ],
    "tags": [
        {
            "name": "User"
        },
        {
            "name": "UserFeedback"
        },
        {
            "name": "UserAddress"
        },
        {
            "name": "Shop Receipt Transactions"
        },
        {
            "name": "Shop"
        },
        {
            "name": "ShopListing"
        },
        {
            "name": "Shop Section"
        },
        {
            "name": "Shop Receipt"
        },
        {
            "name": "Payment"
        },
        {
            "name": "Ledger Entry"
        },
        {
            "name": "ShopListing VariationImage"
        },
        {
            "name": "ShopListing Translation"
        },
        {
            "name": "ShopListing ShippingProfile"
        },
        {
            "name": "ShopListing Inventory"
        },
        {
            "name": "ShopListing Offering"
        },
        {
            "name": "ShopListing Product"
        },
        {
            "name": "ShopListing Image"
        },
        {
            "name": "ShopListing File"
        },
        {
            "name": "Country"
        }
    ],
    "x-tagGroups": [
        {
            "name": "Country Management",
            "tags": ["Country"]
        },
        {
            "name": "Listing Management",
            "tags": [
                "ShopListing",
                "ShopListing File",
                "ShopListing Image",
                "ShopListing Inventory",
                "ShopListing Offering",
                "ShopListing Product",
                "ShopListing ShippingProfile",
                "ShopListing Translation",
                "ShopListing VariationImage"
            ]
        },
        {
            "name": "Payment Management",
            "tags": ["Ledger Entry", "Payment"]
        },
        {
            "name": "Receipt Management",
            "tags": ["Shop Receipt", "Shop Receipt Transactions"]
        },
        {
            "name": "Shop Management",
            "tags": ["Shop", "Shop Section"]
        },
        {
            "name": "User Management",
            "tags": ["User", "UserAddress", "UserFeedback"]
        }
    ],
    "paths": {
        "/v3/public/openapi/countries/{country_id}": {
            "get": {
                "operationId": "getCountry",
                "description": "Open API V3 to retrieve a country by ID.",
                "tags": ["Country"]
            }
        },
        "/v3/public/openapi/countries": {
            "get": {
                "operationId": "getCountries",
                "description": "OpenAPI V3 endpoint to find all countries.",
                "tags": ["Country"]
            }
        },
        "/v3/application/feedback": {
            "get": {
                "operationId": "getPublicUserFeedback",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nOpen API V3 endpoint to retrieve UserFeedback written by or received by a User.",
                "tags": ["UserFeedback"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["feedback_r"]
                    }
                ]
            }
        },
        "/v3/application/listings": {
            "post": {
                "operationId": "createListing",
                "description": "Creates a new listing",
                "tags": ["ShopListing"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            },
            "get": {
                "operationId": "getListings",
                "description": "Endpoint to list Listings that belong to a Shop. Listings can be filtered using the 'state' param.",
                "tags": ["ShopListing"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_r"]
                    }
                ]
            }
        },
        "/v3/application/listings/{listing_id}": {
            "delete": {
                "operationId": "deleteListing",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nOpen API V3 endpoint to delete a ShopListing.",
                "tags": ["ShopListing"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_d"]
                    }
                ]
            },
            "get": {
                "operationId": "getListing",
                "description": "Get a listing",
                "tags": ["ShopListing"]
            },
            "put": {
                "operationId": "updateListing",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nUpdates a ShopListing.",
                "tags": ["ShopListing"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/listings/{listing_id}/files/{listing_file_id}": {
            "delete": {
                "operationId": "deleteListingFile",
                "description": "Deletes a ShopListingFile from the given ShopListing. If the ShopListingFile being deleted is the last ShopListingFile for a digital ShopListing, the ShopListing will be converted to a physical ShopListing. Returns the remaining ShopListingFile records associated with the given ShopListing.",
                "tags": ["ShopListing File"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            },
            "get": {
                "operationId": "getListingFile",
                "description": "Get a single ShopListingFile associated with the given digital ShopListing. The endpoint will return an empty result set for physical ShopListing records.",
                "tags": ["ShopListing File"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_r"]
                    }
                ]
            }
        },
        "/v3/application/listings/{listing_id}/files": {
            "get": {
                "operationId": "getAllListingFiles",
                "description": "Get all ShopListingFile records for the given digital ShopListing. This endpoint will return an empty result set for physical ShopListing records.",
                "tags": ["ShopListing File"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_r"]
                    }
                ]
            },
            "post": {
                "operationId": "uploadListingFile",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nUpload a new ListingFile, or attach an existing file to the given ShopListing. You must either provide the listing_file_id of an existing ListingFile, or the name and file data of a new ListingFile that you are uploading. If you are attaching a ListingFile to a physica[...]",
                "tags": ["ShopListing File"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/listings/active": {
            "get": {
                "operationId": "findAllListingsActive",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nA list of all active listings on Etsy paginated by their creation date. Without sort_order listings will be returned newest-first by default.",
                "tags": ["ShopListing"]
            }
        },
        "/v3/application/listings/{listing_id}/images/{listing_image_id}": {
            "delete": {
                "operationId": "deleteListingImage",
                "description": "Open API V3 endpoint to delete a listing image. A copy of the file remains on our servers, and so a deleted image may be re-associated with the listing without re-uploading the original image; see uploadListingImage.",
                "tags": ["ShopListing Image"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/openapi/listings/{listing_id}/images/{listing_image_id}": {
            "get": {
                "operationId": "getListingImage",
                "description": "Retrieves a ListingImage resource by ID.",
                "tags": ["ShopListing Image"]
            }
        },
        "/v3/application/openapi/listings/{listing_id}/images": {
            "get": {
                "operationId": "getListingImages",
                "description": "Retrieves all ListingImage resources for Listing.",
                "tags": ["ShopListing Image"]
            }
        },
        "/v3/application/listings/{listing_id}/images": {
            "post": {
                "operationId": "uploadListingImage",
                "description": "Uploads a ListingImage.\n\nA new ListingImage can be uploaded via the image param. A previously deleted ListingImage can be re-associated with a Listing via the listing_image_id param. Only one param should be included per request; if both are present in the request, the endpoint will upload the provided image.",
                "tags": ["ShopListing Image"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/listings/{listing_id}/inventory": {
            "get": {
                "operationId": "getListingInventory",
                "description": "Get the inventory for a listing. When a listing has not been edited using the Etsy.com inventory tools, it will have no inventory records. This endpoint returns SKU data if you're the owner of the inventory records being fetched.",
                "tags": ["ShopListing Inventory"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_r"]
                    }
                ]
            },
            "put": {
                "operationId": "updateListingInventory",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nUpdate the inventory for a listing. The update will fail if the supplied values for product sku and offering quantity and price are incompatible with the supplied values of the 'on_property_*' fields. When supplying a price, supply a float equivalent to amount divided [...]",
                "tags": ["ShopListing Inventory"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/listings/{listing_id}/products/{product_id}": {
            "get": {
                "operationId": "getListingProduct",
                "description": "Open API V3 endpoint to retrieve a ListingProduct by ID.",
                "tags": ["ShopListing Product"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/listings/{listing_id}/products/{product_id}/offerings/{product_offering_id}": {
            "get": {
                "operationId": "getListingOffering",
                "description": "Get an Offering for a Listing",
                "tags": ["ShopListing Offering"]
            }
        },
        "/v3/application/listings/{listing_id}/properties": {
            "get": {
                "operationId": "getListingProperties",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nGet a listing's properties",
                "tags": ["ShopListing"]
            }
        },
        "/v3/application/listings/{listing_id}/properties/{property_id}": {
            "put": {
                "operationId": "updateListingProperty",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nUpdate or populate properties for a Listing. Either values or value_ids is required.",
                "tags": ["ShopListing"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/listings/shipping-profiles": {
            "post": {
                "operationId": "createListingShippingProfile",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nCreates a new ShippingProfile.",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/listings/shipping-profiles/{shipping_profile_id}": {
            "delete": {
                "operationId": "deleteListingShippingProfile",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nOpen API V3 endpoint to delete a ShippingProfile by given id.",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            },
            "get": {
                "operationId": "getListingShippingProfile",
                "description": "Open API V3 endpoint to retrieve a ListingShippingProfile by id.",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_r"]
                    }
                ]
            },
            "put": {
                "operationId": "updateListingShippingProfile",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nOpen API V3 endpoint to update a ShippingProfile.",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/listings/shipping-profiles/destinations": {
            "post": {
                "operationId": "createListingShippingProfileDestination",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nCreates a new ListingShippingProfileDestination.",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/listings/shipping-profiles/destinations/{shipping_profile_destination_id}": {
            "delete": {
                "operationId": "deleteListingShippingProfileDestination",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nOpen API V3 endpoint to delete a ListingShippingProfileDestination by the given id.",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            },
            "put": {
                "operationId": "updateListingShippingProfileDestination",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nUpdates an existing ListingShippingProfileDestination.",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/listings/shipping-profiles/{shipping_profile_id}/destinations": {
            "get": {
                "operationId": "getListingShippingProfileDestinationsByShippingProfile",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nOpen API V3 endpoint to retrieve a set of ListingShippingProfileDestination objects associated to a ListingShippingProfile.",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_r"]
                    }
                ]
            }
        },
        "/v3/application/shipping-profiles": {
            "get": {
                "operationId": "getListingShippingProfiles",
                "description": "Open API V3 endpoint to retrieve a set of ShippingProfile objects associated to a User.",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_r"]
                    }
                ]
            }
        },
        "/v3/application/listings/shipping-profiles/{shipping_profile_id}/upgrades": {
            "post": {
                "operationId": "createListingShippingProfileUpgrade",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nCreates a new ListingShippingProfileUpgrade.",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            },
            "get": {
                "operationId": "getListingShippingProfileUpgrades",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nRetrieve a set of ListingShippingProfileUpgrades associated to a ShippingProfile.",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_r"]
                    }
                ]
            }
        },
        "/v3/application/listings/{listing_id}/transactions": {
            "get": {
                "operationId": "getShopReceiptTransactionsByListing",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nOpen API V3 to retrieve a set of ShopTransaction resources associated to a Listing.",
                "tags": ["Shop Receipt Transactions"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/listings/{listing_id}/translations/{language}": {
            "post": {
                "operationId": "createListingTranslation",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nCreates a ListingTranslation by listing_id and language",
                "tags": ["ShopListing Translation"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            },
            "get": {
                "operationId": "getListingTranslation",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nGet a Translation for a Listing in the given language",
                "tags": ["ShopListing Translation"]
            },
            "put": {
                "operationId": "updateListingTranslation",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nUpdates a ListingTranslation by listing_id and language",
                "tags": ["ShopListing Translation"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/listings/{listing_id}/variation-images": {
            "get": {
                "operationId": "getListingVariationImages",
                "description": "Gets all variation images on a listing.",
                "tags": ["ShopListing VariationImage"]
            },
            "post": {
                "operationId": "updateVariationImages",
                "description": "Creates variation images on a listing.\n\nvariation_images is an array with inputs for the property_id, value_id, and image_id fields. image_ids are associated with a ListingImage on the Listing associated with the provided listing_id. property_id and value_id pairs are associated with a ListingProduct on the Listing associated with the provided listing_id. variation_images does not contain any duplicates. variation_images does not contain more than one property_i[...]",
                "tags": ["ShopListing VariationImage"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/payment-account/ledger-entries": {
            "get": {
                "operationId": "getShopPaymentAccountLedgerEntries",
                "description": "Get a Shop Payment Account Ledger's Entries",
                "tags": ["Ledger Entry"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/payment-account/ledger-entries/payments": {
            "get": {
                "operationId": "getPaymentAccountLedgerEntryPayments",
                "description": "Get a Payment from a PaymentAccount Ledger Entry ID, if applicable",
                "tags": ["Payment"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/receipts/{receipt_id}/payments": {
            "get": {
                "operationId": "getShopPaymentByReceiptId",
                "description": "Open API V3 to get a Payment by Shop Receipt ID",
                "tags": ["Payment"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/payments": {
            "get": {
                "operationId": "getPayments",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nGet Payments by their IDs",
                "tags": ["Payment"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/receipts/{receipt_id}": {
            "get": {
                "operationId": "getShopReceipt",
                "description": "Open API V3 endpoint to retreive a Receipt by id",
                "tags": ["Shop Receipt"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/receipts": {
            "get": {
                "operationId": "getShopReceipts",
                "description": "Open API V3 endpoint to find ShopReceipt for a given Shop",
                "tags": ["Shop Receipt"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/receipts/{receipt_id}/tracking": {
            "post": {
                "operationId": "createReceiptShipment",
                "description": "Submit tracking information for a ShopReceipt. If send_bcc is true, the shipping notification will be sent to the seller as well. Each time you successfully submit tracking info, a notification email will be sent to the buyer User. If tracking_code and carrier_name aren't sent the receipt is marked as shipped only. Creates a ShopReceiptShipment for the given receipt_id. ",
                "tags": ["Shop Receipt"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_w"]
                    }
                ]
            }
        },
        "/v3/application/receipts/{receipt_id}/transactions": {
            "get": {
                "operationId": "getShopReceiptTransactionsByReceipt",
                "description": "Retrieves a set of ShopTransaction objects associated to a ShopReceipt.",
                "tags": ["Shop Receipt Transactions"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/shops/feedback": {
            "get": {
                "operationId": "getShopUserFeedback",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nOpen API V3 endpoint to retrieve UserFeedback left for a Shop.",
                "tags": ["UserFeedback"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["feedback_r"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}": {
            "get": {
                "operationId": "getShop",
                "description": "Open API V3 to retrieve a shop by ID.",
                "tags": ["Shop"]
            },
            "put": {
                "operationId": "updateShop",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nOpen API V3 to update a shop by ID.",
                "tags": ["Shop"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["shops_r", "shops_w"]
                    }
                ]
            }
        },
        "/v3/application/users/{user_id}/shops": {
            "get": {
                "operationId": "getShopByOwnerUserId",
                "description": "Open API V3 to retrieve the Shop associated to a User.",
                "tags": ["Shop"]
            }
        },
        "/v3/application/shops": {
            "get": {
                "operationId": "getShops",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nOpen API V3 endpoint to find Shop resources. If there is a shop_name parameter, finds Shop resources with shop_name starting with this value.",
                "tags": ["Shop"]
            }
        },
        "/v3/application/shops/sections": {
            "post": {
                "operationId": "createShopSection",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nOpen API V3 endpoint to create a new ShopSection.",
                "tags": ["Shop Section"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["shops_w"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/sections/{shop_section_id}": {
            "get": {
                "operationId": "getShopSection",
                "description": "Open API V3 to retrieve a ShopSection resource by id and shop_id.",
                "tags": ["Shop Section"]
            }
        },
        "/v3/application/shops/{shop_id}/sections": {
            "get": {
                "operationId": "getShopSections",
                "description": "Open API V3 to retrieve a set of ShopSection objects associated to a Shop.",
                "tags": ["Shop Section"]
            }
        },
        "/v3/application/shops/{shop_id}/sections/listings": {
            "get": {
                "operationId": "getListingsByShopSectionId",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nFetch all Listings within a Shop's ShopSection.",
                "tags": ["ShopListing"]
            }
        },
        "/v3/application/transactions/{transaction_id}": {
            "get": {
                "operationId": "getShopReceiptTransaction",
                "description": "Retrieves a ShopTransaction by id.",
                "tags": ["Shop Receipt Transactions"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/transactions": {
            "get": {
                "operationId": "getShopReceiptTransactionsByShop",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nOpen API V3 to retrieve a set of ShopTransaction resources associated to a Shop.",
                "tags": ["Shop Receipt Transactions"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/user/addresses": {
            "get": {
                "operationId": "getUserAddresses",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nOpen API V3 endpoint to retrieve UserAddresses for a User.",
                "tags": ["UserAddress"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["address_r"]
                    }
                ]
            }
        },
        "/v3/application/users/feedback": {
            "get": {
                "operationId": "getMemberUserFeedback",
                "description": "<div class=\"wt-alert wt-alert--inline wt-alert--status-02 wt-mb-xs-2\"><p class=\"wt-text-body-01\">This endpoint isn't functional but we welcome feedback on the proposed schema below.</p></div>\n\nOpen API V3 endpoint to retrieve UserFeedback left by a User.",
                "tags": ["UserFeedback"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["feedback_r"]
                    }
                ]
            }
        },
        "/v3/application/users/{user_id}": {
            "get": {
                "operationId": "getUser",
                "description": "Open API V3 to retrieve a user by ID.",
                "tags": ["User"]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "api_key": {
                "type": "apiKey",
                "name": "x-api-key",
                "in": "header",
                "description": "Every request to a v3 API endpoint must include this data, with your application's API key as the value."
            },
            "oauth2": {
                "type": "oauth2",
                "description": "The v3 API supports authenticating via OAuth 2.0. More information about Etsy's specific implementation of OAuth2 can be found [here](/developers/documentation/getting_started/oauth2).",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://www.etsy.com/oauth/connect",
                        "tokenUrl": "https://openapi.etsy.com/v3/public/oauth/token",
                        "scopes": {
                            "address_r": "see billing and shipping addresses",
                            "address_w": "update billing and shipping addresses",
                            "billing_r": "see all billing statement data",
                            "cart_r": "read shopping carts",
                            "cart_w": "add/remove from shopping carts",
                            "email_r": "Read a member's email address",
                            "favorites_r": "see private favorites",
                            "favorites_w": "add/remove favorites",
                            "feedback_r": "see purchase info in feedback",
                            "listings_d": "delete listings",
                            "listings_r": "see all listings (including expired etc)",
                            "listings_w": "create/edit listings",
                            "profile_r": "see all profile data",
                            "profile_w": "update user profile, avatar, etc",
                            "recommend_r": "see recommended listings",
                            "recommend_w": "accept/reject recommended listings",
                            "shops_r": "see private shop info",
                            "shops_w": "update shop",
                            "transactions_r": "see all checkout/payment data",
                            "transactions_w": "update receipts"
                        }
                    }
                }
            }
        }
    }
}
