{
    "openapi": "3.0.2",
    "info": {
        "title": "Etsy OpenAPI",
        "description": "<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API reference documents endpoints are meant to replace <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://www.etsy.com/developers/documentation\">Etsy's current Open API</a> this year. Use of the API is subject to the <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://www.etsy.com/legal[...]",
        "termsOfService": "https://www.etsy.com/legal/api",
        "contact": {
            "email": "developers@etsy.com"
        },
        "version": "3.0.0",
        "x-logo": {
            "url": "https://img0.etsystatic.com/site-assets/open-api/etsy_logo.png",
            "backgroundColor": "#FFFFFF",
            "altText": "Etsy Logo"
        }
    },
    "servers": [
        {
            "url": "https://openapi.etsy.com",
            "description": "Base url for all Integrations endpoints."
        }
    ],
    "security": [
        {
            "api_key": []
        }
    ],
    "tags": [
        {
            "name": "User"
        },
        {
            "name": "UserAddress"
        },
        {
            "name": "Shop Receipt Transactions"
        },
        {
            "name": "Shop"
        },
        {
            "name": "ShopListing"
        },
        {
            "name": "Shop Section"
        },
        {
            "name": "SellerTaxonomy"
        },
        {
            "name": "Review"
        },
        {
            "name": "Shop Receipt"
        },
        {
            "name": "Other"
        },
        {
            "name": "Payment"
        },
        {
            "name": "Ledger Entry"
        },
        {
            "name": "ShopListing VariationImage"
        },
        {
            "name": "ShopListing Translation"
        },
        {
            "name": "ShopListing ShippingProfile"
        },
        {
            "name": "ShopListing Inventory"
        },
        {
            "name": "ShopListing Offering"
        },
        {
            "name": "ShopListing Product"
        },
        {
            "name": "ShopListing Image"
        },
        {
            "name": "ShopListing File"
        }
    ],
    "x-tagGroups": [
        {
            "name": "Listing Management",
            "tags": [
                "SellerTaxonomy",
                "ShopListing",
                "ShopListing File",
                "ShopListing Image",
                "ShopListing Inventory",
                "ShopListing Offering",
                "ShopListing Product",
                "ShopListing ShippingProfile",
                "ShopListing Translation",
                "ShopListing VariationImage"
            ]
        },
        {
            "name": "Other",
            "tags": ["Other"]
        },
        {
            "name": "Payment Management",
            "tags": ["Ledger Entry", "Payment"]
        },
        {
            "name": "Receipt Management",
            "tags": ["Shop Receipt", "Shop Receipt Transactions"]
        },
        {
            "name": "Review Management",
            "tags": ["Review"]
        },
        {
            "name": "Shop Management",
            "tags": ["Shop", "Shop Section"]
        },
        {
            "name": "User Management",
            "tags": ["User", "UserAddress"]
        }
    ],
    "paths": {
        "/v3/application/shops/{shop_id}/listings": {
            "post": {
                "operationId": "createListing",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/listings/{listing_id}": {
            "delete": {
                "operationId": "deleteListing",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_d"]
                    }
                ]
            },
            "get": {
                "operationId": "getListing",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing"]
            }
        },
        "/v3/application/listings/{listing_id}/files/{listing_file_id}": {
            "delete": {
                "operationId": "deleteListingFile",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing File"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            },
            "get": {
                "operationId": "getListingFile",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing File"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_r"]
                    }
                ]
            }
        },
        "/v3/application/listings/{listing_id}/files": {
            "get": {
                "operationId": "getAllListingFiles",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing File"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_r"]
                    }
                ]
            },
            "post": {
                "operationId": "uploadListingFile",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-01 wt-mr-xs-2\"> Feedback only </span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">Development for this endpoint is[...]",
                "tags": ["ShopListing File"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/listings/active": {
            "get": {
                "operationId": "findAllListingsActive",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing"]
            }
        },
        "/v3/application/shops/{shop_id}/listings/active": {
            "get": {
                "operationId": "findAllActiveListingsByShop",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing"]
            }
        },
        "/v3/application/shops/{shop_id}/listings/{listing_id}/images/{listing_image_id}": {
            "delete": {
                "operationId": "deleteListingImage",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing Image"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/shop/{shop_id}/listings/{listing_id}/images/{listing_image_id}": {
            "get": {
                "operationId": "getListingImage",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing Image"]
            }
        },
        "/v3/application/shops/{shop_id}/listings/{listing_id}/images": {
            "get": {
                "operationId": "getListingImages",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing Image"]
            },
            "post": {
                "operationId": "uploadListingImage",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing Image"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/listings/{listing_id}/inventory": {
            "get": {
                "operationId": "getListingInventory",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing Inventory"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_r"]
                    }
                ]
            },
            "put": {
                "operationId": "updateListingInventory",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing Inventory"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/listings/{listing_id}/inventory/products/{product_id}": {
            "get": {
                "operationId": "getListingProduct",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing Product"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/listings/{listing_id}/products/{product_id}/offerings/{product_offering_id}": {
            "get": {
                "operationId": "getListingOffering",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing Offering"]
            }
        },
        "/v3/application/listings": {
            "get": {
                "operationId": "getListings",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_r"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/listings/featured": {
            "get": {
                "operationId": "getFeaturedListingsByShop",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing"]
            }
        },
        "/v3/application/shops/{shop_id}/listings/{listing_id}/properties/{property_id}": {
            "delete": {
                "operationId": "deleteListingProperty",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/listings/{listing_id}/properties/{property_id}": {
            "get": {
                "operationId": "getListingProperty",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-01 wt-mr-xs-2\"> Feedback only </span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">Development for this endpoint is[...]",
                "tags": ["ShopListing"]
            },
            "put": {
                "operationId": "updateListingProperty",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-01 wt-mr-xs-2\"> Feedback only </span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">Development for this endpoint is[...]",
                "tags": ["ShopListing"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/listings/{listing_id}/properties": {
            "get": {
                "operationId": "getListingProperties",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing"]
            }
        },
        "/v3/application/listings/shipping-carriers": {
            "get": {
                "operationId": "getShippingCarriers",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/listings/shipping-profiles": {
            "post": {
                "operationId": "createListingShippingProfile",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            },
            "get": {
                "operationId": "getListingShippingProfiles",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_r"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/listings/shipping-profiles/{shipping_profile_id}": {
            "delete": {
                "operationId": "deleteListingShippingProfile",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            },
            "get": {
                "operationId": "getListingShippingProfile",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_r"]
                    }
                ]
            },
            "put": {
                "operationId": "updateListingShippingProfile",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/listings/shipping-profiles/{shipping_profile_id}/destinations": {
            "post": {
                "operationId": "createListingShippingProfileDestination",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            },
            "get": {
                "operationId": "getListingShippingProfileDestinationsByShippingProfile",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_r"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/listings/shipping-profiles/destinations/{shipping_profile_destination_id}": {
            "delete": {
                "operationId": "deleteListingShippingProfileDestination",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            },
            "put": {
                "operationId": "updateListingShippingProfileDestination",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/listings/shipping-profiles/{shipping_profile_id}/upgrades": {
            "post": {
                "operationId": "createListingShippingProfileUpgrade",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            },
            "get": {
                "operationId": "getListingShippingProfileUpgrades",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_r"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/listings/shipping-profiles/{shipping_profile_id}/upgrades/{upgrade_id}": {
            "delete": {
                "operationId": "deleteListingShippingProfileUpgrade",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            },
            "put": {
                "operationId": "updateListingShippingProfileUpgrade",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing ShippingProfile"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/listings/{listing_id}/transactions": {
            "get": {
                "operationId": "getShopReceiptTransactionsByListing",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Shop Receipt Transactions"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/listings/{listing_id}/translations/{language}": {
            "post": {
                "operationId": "createListingTranslation",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-01 wt-mr-xs-2\"> Feedback only </span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">Development for this endpoint is[...]",
                "tags": ["ShopListing Translation"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            },
            "get": {
                "operationId": "getListingTranslation",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-01 wt-mr-xs-2\"> Feedback only </span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">Development for this endpoint is[...]",
                "tags": ["ShopListing Translation"]
            },
            "put": {
                "operationId": "updateListingTranslation",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-01 wt-mr-xs-2\"> Feedback only </span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">Development for this endpoint is[...]",
                "tags": ["ShopListing Translation"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/listings/{listing_id}": {
            "put": {
                "operationId": "updateListing",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/listings/{listing_id}/variation-images": {
            "get": {
                "operationId": "getListingVariationImages",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing VariationImage"]
            },
            "post": {
                "operationId": "updateVariationImages",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing VariationImage"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["listings_w"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/payment-account/ledger-entries": {
            "get": {
                "operationId": "getShopPaymentAccountLedgerEntries",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Ledger Entry"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/payment-account/ledger-entries/payments": {
            "get": {
                "operationId": "getPaymentAccountLedgerEntryPayments",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Payment"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/receipts/{receipt_id}/payments": {
            "get": {
                "operationId": "getShopPaymentByReceiptId",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Payment"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/payments": {
            "get": {
                "operationId": "getPayments",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Payment"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/openapi-ping": {
            "get": {
                "operationId": "ping",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Other"]
            }
        },
        "/v3/application/shops/{shop_id}/receipts/{receipt_id}": {
            "get": {
                "operationId": "getShopReceipt",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Shop Receipt"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/receipts": {
            "get": {
                "operationId": "getShopReceipts",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Shop Receipt"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/receipts/{receipt_id}/listings": {
            "get": {
                "operationId": "getListingsByShopReceipt",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["ShopListing"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/receipts/{receipt_id}/tracking": {
            "post": {
                "operationId": "createReceiptShipment",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Shop Receipt"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_w"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/receipts/{receipt_id}/transactions": {
            "get": {
                "operationId": "getShopReceiptTransactionsByReceipt",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Shop Receipt Transactions"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/shops/{shop_id}/reviews": {
            "get": {
                "operationId": "getReviewsByShop",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Review"]
            }
        },
        "/v3/application/seller-taxonomy/nodes": {
            "get": {
                "operationId": "getSellerTaxonomyNodes",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["SellerTaxonomy"]
            }
        },
        "/v3/application/seller-taxonomy/nodes/{taxonomy_id}/properties": {
            "get": {
                "operationId": "getPropertiesByTaxonomyId",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["SellerTaxonomy"]
            }
        },
        "/v3/application/shops/{shop_id}": {
            "get": {
                "operationId": "getShop",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Shop"]
            },
            "put": {
                "operationId": "updateShop",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Shop"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["shops_r", "shops_w"]
                    }
                ]
            }
        },
        "/v3/application/users/{user_id}/shops": {
            "get": {
                "operationId": "getShopByOwnerUserId",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Shop"]
            }
        },
        "/v3/application/shops": {
            "get": {
                "operationId": "findShops",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Shop"]
            }
        },
        "/v3/application/shops/{shop_id}/sections": {
            "post": {
                "operationId": "createShopSection",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Shop Section"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["shops_w"]
                    }
                ]
            },
            "get": {
                "operationId": "getShopSections",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Shop Section"]
            }
        },
        "/v3/application/shops/{shop_id}/sections/{shop_section_id}": {
            "get": {
                "operationId": "getShopSection",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Shop Section"]
            }
        },
        "/v3/application/shops/{shop_id}/sections/listings": {
            "get": {
                "operationId": "getListingsByShopSectionId",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-01 wt-mr-xs-2\"> Feedback only </span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">Development for this endpoint is[...]",
                "tags": ["ShopListing"]
            }
        },
        "/v3/application/transactions/{transaction_id}": {
            "get": {
                "operationId": "getShopReceiptTransaction",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Shop Receipt Transactions"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/transactions": {
            "get": {
                "operationId": "getShopReceiptTransactionsByShop",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["Shop Receipt Transactions"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["transactions_r"]
                    }
                ]
            }
        },
        "/v3/application/user/addresses/{user_address_id}": {
            "get": {
                "operationId": "getUserAddress",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-01 wt-mr-xs-2\"> Feedback only </span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">Development for this endpoint is[...]",
                "tags": ["UserAddress"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["address_r"]
                    }
                ]
            }
        },
        "/v3/application/user/addresses": {
            "get": {
                "operationId": "getUserAddresses",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["UserAddress"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["address_r"]
                    }
                ]
            }
        },
        "/v3/application/users/{user_id}": {
            "get": {
                "operationId": "getUser",
                "description": "<div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><span class=\"wt-badge wt-badge--notification-03 wt-mr-xs-2\">Alpha</span><a class=\"wt-text-link\" href=\"https://github.com/etsy/open-api/issues/new/choose\" target=\"_blank\" rel=\"noopener noreferrer\">Give feedback</a></div><div class=\"wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\"><p class=\"wt-text-body-01 banner-text\">This endpoint is ready for use as defined [...]",
                "tags": ["User"],
                "security": [
                    {
                        "api_key": [],
                        "oauth2": ["email_r"]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "api_key": {
                "type": "apiKey",
                "name": "x-api-key",
                "in": "header",
                "description": "Every request to a v3 API endpoint must include this data, with your application's API key as the value."
            },
            "oauth2": {
                "type": "oauth2",
                "description": "The v3 API supports authenticating via OAuth 2.0. More information about Etsy's specific implementation of OAuth2 can be found [here](/developers/documentation/getting_started/oauth2).",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://www.etsy.com/oauth/connect",
                        "tokenUrl": "https://openapi.etsy.com/v3/public/oauth/token",
                        "scopes": {
                            "address_r": "see billing and shipping addresses",
                            "address_w": "update billing and shipping addresses",
                            "billing_r": "see all billing statement data",
                            "cart_r": "read shopping carts",
                            "cart_w": "add/remove from shopping carts",
                            "email_r": "Read a member's email address",
                            "favorites_r": "see private favorites",
                            "favorites_w": "add/remove favorites",
                            "feedback_r": "see purchase info in feedback",
                            "listings_d": "delete listings",
                            "listings_r": "see all listings (including expired etc)",
                            "listings_w": "create/edit listings",
                            "profile_r": "see all profile data",
                            "profile_w": "update user profile, avatar, etc",
                            "recommend_r": "see recommended listings",
                            "recommend_w": "accept/reject recommended listings",
                            "shops_r": "see private shop info",
                            "shops_w": "update shop",
                            "transactions_r": "see all checkout/payment data",
                            "transactions_w": "update receipts"
                        }
                    }
                }
            }
        }
    }
}
