name: 💡 API Design Proposal
description: Propose an enhancement or change to existing OpenAPI design
title: "[ENDPOINT]: Proposed design change for <endpoint name here> "
labels: "API Design "
body:
 - type: markdown
   attributes: 
     value: |
       Thanks for taking the time to fill out this proposal!
 - type: checkboxes
   attributes:
     label: Is there an existing issue for this?
     description: Please search to see if an ticket already exists for this proposal.
     options:
     - label: I have searched the existing tickets
       required: true
 - type: textarea
   attributes:
     label: Current Endpoint Design
     description: What in the current endpoint design do you think is missing or find confusing?
   validations:
     required: true
 - type: textarea
   attributes:
     label: Proposed Endpoint Design Change
     description: Add information about your proposed change.
   validations:
     required: true
 - type: textarea
   attributes:
     label: Why are you proposing this change?
     description: Please provide a reason for the change you're proposing.
   validations:
     required: true
