name: Test Ticket (Bug)
description: Submit a bug report to help us improve
title: "[BUG]: "
labels: "Bug"
body:
 - type: markdown
   attributes: 
     value: |
       Thanks for taking the time to fill out this bug report!
 - type: checkboxes
   attributes:
     label: Is there an existing issue for this?
     description: Please search to see if an issue already exists for the bug you encountered.
     options:
     - label: I have searched the existing issues
       required: true
 - type: textarea
   attributes:
     label: Describe the bug
     description: A concise overview of what the bug is.
   validations:
     required: true
 - type: textarea
   attributes:
     label: Steps to reproduce
     description: What steps can we take to reproduce the bug?
     placeholder: |
       1. In this environment...
       2. With this config...
       3. Run '...'
       4. See error...
   validations:
     required: true
 - type: textarea
   attributes:
     label: Expected behavior
     description: When the above steps are completed, what is correct expected result?
   validations:
     required: true
 - type: textarea
   attributes:
     label: Additional context
     description: Any additional information to share?
