contact_links:
    - name: 🤔 Questions and Help
      url: "mailto:developers@etsy.com"
      about: For questions and help regarding OpenAPI v2, or your implementation of the new OpenAPI v3, please email us at developers@etsy.com