blank_issues_enabled: false
contact_links:
    - name: 💬 Discussions
      url: https://github.com/etsy/open-api/discussions
      about: Engage with the Etsy Open API community via GitHub discussions where you'll find announcements, Q&A, and more. 
    - name: 📖 Developer Documentation
      url: https://developers.etsy.com/documentation/
      about: The Etsy Open API v3 documentation with guides, references, tutorials, and more. 
