name: 📄 Documentation Issue
description: Suggest any changes to the OpenAPI Documentation
title: "[DOCS]: "
labels: "Documentation"
body:
 - type: markdown
   attributes: 
     value: |
       Thanks for taking the time to fill out this documentation issue report!
 - type: checkboxes
   attributes:
     label: Is there an existing issue for this?
     description: Please search to see if an issue already exists for the issue you encountered.
     options:
     - label: I have searched the existing issues
       required: true
 - type: input
   attributes:
     label: Link to Documentation Issue
     description: Please add a link here for which part of the documentation you're reporting an issue.
   validations:
     required: true
 - type: textarea
   attributes:
     label: What would you like to change?
     description: Please describe your proposed change here.
   validations:
     required: true
 - type: textarea
   attributes:
     label: Why are you proposing this change?
     description: Please provide a reason for the change you're proposing.
   validations:
     required: false
